"""Shared helpers for scheduled-task conversation parsing and activity collection.

Shared by skills like `newsletter` and `dream` that inspect recent scheduled runs
to summarize activity or avoid repeating recently performed work.
"""

import json
import logging
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

from decafclaw.conversation_paths import iter_conversation_archives

log = logging.getLogger(__name__)

CONV_ID_RE = re.compile(r"^schedule-(.+)-(\d{8}-\d{6})$")
VAULT_WRITE_TOOLS = {"vault_write"}
STATUS_TOKEN_RE = re.compile(r"^[A-Z][A-Z0-9_]{1,40}$")


def parse_scheduled_conv_id(conv_id: str) -> tuple[str, datetime] | None:
    """Parse `schedule-{name}-{YYYYMMDD-HHMMSS}`. Returns None if not scheduled.

    The timestamp in the conv_id is generated by `schedules.py` using
    ``datetime.now().strftime(...)`` — naive local time. Treat it as local
    time and convert to UTC so window filters work correctly across timezones.
    """
    match = CONV_ID_RE.match(conv_id)
    if not match:
        return None
    name = match.group(1)
    try:
        local_ts = datetime.strptime(match.group(2), "%Y%m%d-%H%M%S")
        local_tz = datetime.now().astimezone().tzinfo or timezone.utc
        ts = local_ts.replace(tzinfo=local_tz).astimezone(timezone.utc)
    except ValueError:
        return None
    return name, ts


def is_status_token(content: str) -> bool:
    """Return True if `content` looks like a status marker rather than narrative.

    Scheduled-task agent turns frequently end with a literal status token
    (e.g. `HEARTBEAT_OK`, `OK`, `DONE`) produced by the shared polling-task
    preamble. These are useless as summary source material — if we let them
    win the 'final assistant message' slot, we crowd out the actual narrative.
    """
    stripped = content.strip()
    if not stripped:
        return True
    if "\n" in stripped:
        return False
    return bool(STATUS_TOKEN_RE.match(stripped))


def extract_activity(path: Path) -> tuple[str, list[str]]:
    """Read a conversation JSONL; return (final_assistant_text, vault_pages_touched)."""
    final_text = ""
    touched: list[str] = []
    try:
        with path.open() as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("role") != "assistant":
                    continue
                content = rec.get("content") or ""
                if content and not is_status_token(content):
                    final_text = content
                for call in rec.get("tool_calls") or []:
                    fn = (call.get("function") or {}).get("name")
                    if fn in VAULT_WRITE_TOOLS:
                        try:
                            args = json.loads((call.get("function") or {}).get("arguments") or "{}")
                        except json.JSONDecodeError:
                            continue
                        page = args.get("page")
                        if page:
                            touched.append(page)
    except OSError as exc:
        log.debug("Failed to read %s: %s", path, exc)
    # Deduplicate while preserving insertion order (the same page may be
    # written multiple times in one run if the skill updates it iteratively).
    touched = list(dict.fromkeys(touched))
    return final_text, touched


def collect_scheduled_activity(
    config,
    hours: int = 24,
    skill_name: str | None = None,
    exclude_skill_name: str | None = None,
) -> list[dict]:
    """Gather scheduled-task activity records within `hours`.

    Returns a list of dicts:
      - skill_name: str
      - conv_id: str
      - started_at: str (ISO 8601 UTC)
      - final_message: str
      - vault_pages_touched: list[str]
    """
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    out: list[dict] = []
    archives = sorted(iter_conversation_archives(config), key=lambda t: t[0])
    for conv_id, path in archives:
        if not conv_id.startswith("schedule-"):
            continue
        parsed = parse_scheduled_conv_id(conv_id)
        if parsed is None:
            continue
        name, ts = parsed
        if skill_name is not None and name != skill_name:
            continue
        if exclude_skill_name is not None and name == exclude_skill_name:
            continue
        if ts < cutoff:
            continue
        final, touched = extract_activity(path)
        out.append(
            {
                "skill_name": name,
                "conv_id": conv_id,
                "started_at": ts.isoformat(),
                "final_message": final,
                "vault_pages_touched": touched,
            }
        )
    return out
