"""Newsletter bundled skill — composes and delivers periodic activity digests."""

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

from decafclaw.mail import send_mail
from decafclaw.media import ToolResult

log = logging.getLogger(__name__)

_config = None
_skill_config: "SkillConfig | None" = None


@dataclass
class SkillConfig:
    window_hours: int = field(
        default=24, metadata={"env_alias": "NEWSLETTER_WINDOW_HOURS"}
    )
    email_enabled: bool = field(
        default=False, metadata={"env_alias": "NEWSLETTER_EMAIL_ENABLED"}
    )
    email_recipients: list[str] = field(
        default_factory=list,
        metadata={"env_alias": "NEWSLETTER_EMAIL_RECIPIENTS"},
    )
    email_subject_prefix: str = field(
        default="[decafclaw newsletter]",
        metadata={"env_alias": "NEWSLETTER_EMAIL_SUBJECT_PREFIX"},
    )
    vault_page_enabled: bool = field(
        default=True, metadata={"env_alias": "NEWSLETTER_VAULT_PAGE_ENABLED"}
    )
    vault_folder: str = field(
        default="agent/journal/newsletters",
        metadata={"env_alias": "NEWSLETTER_VAULT_FOLDER"},
    )


def init(config, skill_config: SkillConfig) -> None:
    """Initialize the newsletter skill. Called by the skill loader on activation."""
    global _config, _skill_config
    _config = config
    _skill_config = skill_config


_CONV_ID_RE = re.compile(r"^schedule-(.+)-(\d{8}-\d{6})$")
_VAULT_WRITE_TOOLS = {"vault_write"}
_SELF_SKILL_NAME = "newsletter"
_STATUS_TOKEN_RE = re.compile(r"^[A-Z][A-Z0-9_]{1,40}$")
_WINDOW_RE = re.compile(r"^\s*(\d+)\s*([hdw])\s*$", re.IGNORECASE)
_WINDOW_UNIT_HOURS = {"h": 1, "d": 24, "w": 24 * 7}


def _parse_window(spec: str) -> int:
    """Parse a compact window spec like ``"24h"``, ``"7d"``, or ``"2w"``
    into an integer number of hours. Raises ValueError on malformed input."""
    match = _WINDOW_RE.match(spec)
    if not match:
        raise ValueError(
            f"invalid window spec {spec!r} — use forms like '24h', '7d', '2w'"
        )
    n = int(match.group(1))
    if n <= 0:
        raise ValueError(f"invalid window spec {spec!r} — must be positive")
    unit = match.group(2).lower()
    return n * _WINDOW_UNIT_HOURS[unit]


def _resolve_hours(window: str, hours: int | None) -> tuple[int, str]:
    """Resolve the active window. ``window`` takes precedence when non-empty;
    otherwise ``hours`` (or the SkillConfig default) is used. Returns
    ``(hours, display)`` where ``display`` is used in tool summary text."""
    if window:
        h = _parse_window(window)
        return h, window.strip()
    if hours is None:
        hours = _skill_config.window_hours if _skill_config is not None else 24
    return hours, f"{hours}h"


def _is_status_token(content: str) -> bool:
    """Return True if `content` looks like a status marker rather than narrative.

    Scheduled-task agent turns frequently end with a literal status token
    (e.g. `HEARTBEAT_OK`, `OK`, `DONE`) produced by the shared polling-task
    preamble. These are useless as newsletter source material — if we let
    them win the "final assistant message" slot, we crowd out the actual
    narrative earlier in the turn. Skip them when selecting final_message.
    """
    stripped = content.strip()
    if not stripped:
        return True
    if "\n" in stripped:
        return False
    return bool(_STATUS_TOKEN_RE.match(stripped))


def _parse_conv_id(conv_id: str) -> tuple[str, datetime] | None:
    """Parse `schedule-{name}-{YYYYMMDD-HHMMSS}`. Returns None if not scheduled.

    The timestamp in the conv_id is generated by `schedules.py` using
    ``datetime.now().strftime(...)`` — naive local time.  Treat it as local
    time and convert to UTC so the 24h window filter works correctly on
    non-UTC hosts (e.g. US/Pacific would otherwise appear 8h ahead of UTC,
    filtering out recent runs).
    """
    match = _CONV_ID_RE.match(conv_id)
    if not match:
        return None
    name = match.group(1)
    try:
        local_ts = datetime.strptime(match.group(2), "%Y%m%d-%H%M%S")
        local_tz = datetime.now().astimezone().tzinfo or timezone.utc
        ts = local_ts.replace(tzinfo=local_tz).astimezone(timezone.utc)
    except ValueError:
        return None
    return name, ts


def _extract_activity(path: Path) -> tuple[str, list[str]]:
    """Read a conversation JSONL; return (final_assistant_text, vault_pages_touched)."""
    final_text = ""
    touched: list[str] = []
    try:
        with path.open() as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("role") != "assistant":
                    continue
                content = rec.get("content") or ""
                if content and not _is_status_token(content):
                    final_text = content
                for call in rec.get("tool_calls") or []:
                    fn = (call.get("function") or {}).get("name")
                    if fn in _VAULT_WRITE_TOOLS:
                        try:
                            args = json.loads(
                                (call.get("function") or {}).get("arguments") or "{}"
                            )
                        except json.JSONDecodeError:
                            continue
                        page = args.get("page")
                        if page:
                            touched.append(page)
    except OSError as exc:
        log.debug("Failed to read %s: %s", path, exc)
    # Deduplicate while preserving insertion order (the same page may be
    # written multiple times in one run if the skill updates it iteratively).
    touched = list(dict.fromkeys(touched))
    return final_text, touched


def _collect_scheduled_activity(ctx, hours: int = 24) -> list[dict]:
    """Gather scheduled-task activity records. Returns the raw list
    used by newsletter_list_scheduled_activity."""
    workspace = Path(ctx.config.workspace_path)
    conv_dir = workspace / "conversations"
    if not conv_dir.is_dir():
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    out: list[dict] = []
    for path in sorted(conv_dir.glob("schedule-*.jsonl")):
        parsed = _parse_conv_id(path.stem)
        if parsed is None:
            continue
        skill_name, ts = parsed
        if skill_name == _SELF_SKILL_NAME:
            continue
        if ts < cutoff:
            continue
        final, touched = _extract_activity(path)
        out.append({
            "skill_name": skill_name,
            "conv_id": path.stem,
            "started_at": ts.isoformat(),
            "final_message": final,
            "vault_pages_touched": touched,
        })
    return out


async def newsletter_list_scheduled_activity(
    ctx, hours: int | None = None, window: str = ""
) -> ToolResult:
    """List scheduled-task activity within the given time window.

    ``window`` is a compact string like ``"7d"``, ``"48h"``, ``"2w"`` and
    takes precedence when provided. ``hours`` is a numeric fallback;
    when neither is provided, the SkillConfig ``window_hours`` default
    (24h) is used.

    Returns one entry per scheduled-task conversation (excluding newsletter's own),
    with skill_name, conv_id, started_at, final_message, and vault_pages_touched.
    """
    try:
        resolved_hours, display = _resolve_hours(window, hours)
    except ValueError as exc:
        return ToolResult(text=f"[error: {exc}]")
    activity = _collect_scheduled_activity(ctx, resolved_hours)
    summary = (
        f"Found {len(activity)} scheduled-task conversation(s) "
        f"in the last {display}."
    )
    return ToolResult(
        text=summary,
        data={"activity": activity, "hours": resolved_hours, "window": display},
    )


def _collect_vault_changes(ctx, hours: int = 24) -> list[dict]:
    """Gather vault markdown files modified in the last `hours` (mtime-based).

    Returns a list of {path (str, relative to vault root), mtime (ISO-8601), size (int)}.
    Excludes files under the newsletter output folder (self-references).
    """
    vault_root = ctx.config.vault_root
    if not vault_root.is_dir():
        return []

    cutoff_ts = (datetime.now(timezone.utc) - timedelta(hours=hours)).timestamp()
    newsletter_folder = None
    if _skill_config is not None:
        newsletter_folder = _skill_config.vault_folder

    out: list[dict] = []
    for path in vault_root.rglob("*.md"):
        try:
            stat = path.stat()
        except OSError:
            continue
        if stat.st_mtime < cutoff_ts:
            continue
        rel = path.relative_to(vault_root).as_posix()
        if newsletter_folder and rel.startswith(newsletter_folder.rstrip("/") + "/"):
            continue
        out.append({
            "path": rel,
            "mtime": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
            "size": stat.st_size,
        })
    out.sort(key=lambda r: r["mtime"])
    return out


async def newsletter_list_vault_changes(
    ctx, hours: int | None = None, window: str = ""
) -> ToolResult:
    """List vault markdown files modified in the given window (mtime-based).

    ``window`` is a compact string like ``"7d"``, ``"48h"``, ``"2w"`` and
    takes precedence when provided. ``hours`` is a numeric fallback;
    when neither is provided, the SkillConfig ``window_hours`` default
    (24h) is used.

    Excludes files under the newsletter's own output folder so subsequent
    newsletters don't self-reference.
    """
    try:
        resolved_hours, display = _resolve_hours(window, hours)
    except ValueError as exc:
        return ToolResult(text=f"[error: {exc}]")
    changes = _collect_vault_changes(ctx, resolved_hours)
    summary = f"Found {len(changes)} vault page change(s) in the last {display}."
    return ToolResult(
        text=summary,
        data={"changes": changes, "hours": resolved_hours, "window": display},
    )


async def newsletter_publish(
    ctx,
    markdown: str,
    subject_hint: str | None = None,
    has_content: bool = True,
    force_delivery: bool = False,
) -> ToolResult:
    """Publish the composed newsletter.

    If invoked interactively (``ctx.task_mode != "scheduled"``) and
    ``force_delivery`` is False, returns the markdown verbatim — no
    archive, no delivery, no state change.

    Under a scheduled run *or* when ``force_delivery`` is True, archives
    locally, delivers to all enabled targets, and advances
    ``last_run.json``. ``force_delivery`` exists for smoke-testing the
    delivery path from ``!newsletter send`` without waiting for cron.
    """
    if ctx.task_mode != "scheduled" and not force_delivery:
        return ToolResult(text=markdown)

    # Scheduled branch
    now = datetime.now(timezone.utc)
    workspace = Path(ctx.config.workspace_path)
    newsletter_dir = workspace / "newsletter"
    archive_dir = newsletter_dir / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    if has_content:
        archive_body = markdown
    else:
        archive_body = f"# {now.strftime('%Y-%m-%d')}\n\n_Nothing to report._\n"

    # Date-suffixed filename with collision handling
    date_str = now.strftime("%Y-%m-%d")
    archive_path = archive_dir / f"{date_str}.md"
    suffix = 0
    while archive_path.exists():
        suffix += 1
        archive_path = archive_dir / f"{date_str}-{suffix}.md"
    archive_path.write_text(archive_body, encoding="utf-8")

    # Advance state
    last_run_path = newsletter_dir / "last_run.json"
    last_run_path.write_text(json.dumps({
        "last_run_utc": now.isoformat(),
        "window_end_utc": now.isoformat(),
    }), encoding="utf-8")

    delivered_targets: list[str] = []
    if has_content and _skill_config is not None:
        # Email delivery
        if _skill_config.email_enabled and _skill_config.email_recipients:
            subject_suffix = subject_hint or now.strftime("%Y-%m-%d")
            subject = f"{_skill_config.email_subject_prefix} {subject_suffix}".strip()
            try:
                await send_mail(
                    ctx.config,
                    to=list(_skill_config.email_recipients),
                    subject=subject,
                    body=markdown,
                )
                delivered_targets.append("email")
            except Exception as exc:  # noqa: BLE001 — isolation boundary
                log.warning("Newsletter email delivery failed: %s", exc)

        # Vault page delivery
        if _skill_config.vault_page_enabled:
            vault_root_path = ctx.config.vault_root
            if vault_root_path.is_dir():
                vault_folder = _skill_config.vault_folder
                # Sandbox check: reject empty, absolute, or path-traversal values.
                folder_ok = True
                if not vault_folder:
                    log.warning(
                        "Newsletter vault_folder is empty — skipping vault-page delivery"
                    )
                    folder_ok = False
                elif Path(vault_folder).is_absolute():
                    log.warning(
                        "Newsletter vault_folder %r is absolute — skipping vault-page delivery",
                        vault_folder,
                    )
                    folder_ok = False
                elif ".." in Path(vault_folder).parts:
                    log.warning(
                        "Newsletter vault_folder %r contains '..' — skipping vault-page delivery",
                        vault_folder,
                    )
                    folder_ok = False
                else:
                    resolved_dir = (vault_root_path / vault_folder).resolve()
                    if not resolved_dir.is_relative_to(vault_root_path.resolve()):
                        log.warning(
                            "Newsletter vault_folder %r resolves outside vault root — "
                            "skipping vault-page delivery",
                            vault_folder,
                        )
                        folder_ok = False

                if folder_ok:
                    try:
                        target_dir = vault_root_path / vault_folder
                        target_dir.mkdir(parents=True, exist_ok=True)
                        target_path = target_dir / f"{date_str}.md"
                        suffix = 0
                        while target_path.exists():
                            suffix += 1
                            target_path = target_dir / f"{date_str}-{suffix}.md"
                        target_path.write_text(markdown, encoding="utf-8")
                        delivered_targets.append("vault_page")
                    except Exception as exc:  # noqa: BLE001
                        log.warning("Newsletter vault-page delivery failed: %s", exc)

    if delivered_targets:
        summary_text = (
            f"Newsletter archived to {archive_path.name}. "
            f"Delivered to: {', '.join(delivered_targets)}."
        )
    elif has_content:
        summary_text = (
            f"Newsletter archived to {archive_path.name}. "
            f"No delivery targets enabled."
        )
    else:
        summary_text = f"Nothing to report; window advanced. Archive: {archive_path.name}."
    return ToolResult(text=summary_text, data={
        "archive_path": str(archive_path),
        "has_content": has_content,
        "delivered_targets": delivered_targets,
    })


# -- Registration -------------------------------------------------------------

TOOLS = {
    "newsletter_list_scheduled_activity": newsletter_list_scheduled_activity,
    "newsletter_list_vault_changes": newsletter_list_vault_changes,
    "newsletter_publish": newsletter_publish,
}

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "newsletter_list_scheduled_activity",
            "description": (
                "List scheduled-task conversations within a time window (excludes "
                "newsletter's own runs). Returns skill_name, conv_id, started_at, "
                "final_message, and vault_pages_touched per conversation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "window": {
                        "type": "string",
                        "description": (
                            "Compact time-range string like '24h', '7d', '2w'. "
                            "Takes precedence over 'hours' when non-empty."
                        ),
                    },
                    "hours": {
                        "type": "integer",
                        "description": (
                            "Numeric window fallback in hours. Defaults to 24 "
                            "(or SkillConfig.window_hours)."
                        ),
                    },
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "newsletter_list_vault_changes",
            "description": (
                "List vault markdown pages created or modified within a time window "
                "(mtime-based). Excludes files under the newsletter's own output folder."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "window": {
                        "type": "string",
                        "description": (
                            "Compact time-range string like '24h', '7d', '2w'. "
                            "Takes precedence over 'hours' when non-empty."
                        ),
                    },
                    "hours": {
                        "type": "integer",
                        "description": (
                            "Numeric window fallback in hours. Defaults to 24 "
                            "(or SkillConfig.window_hours)."
                        ),
                    },
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "newsletter_publish",
            "description": (
                "Publish the composed newsletter. Under a scheduled run, archives "
                "locally, dispatches to configured delivery targets (email, vault page), "
                "and advances last_run.json. Under interactive invocation "
                "(`!newsletter`), returns the markdown as-is with no side effects — "
                "unless `force_delivery` is True, which smoke-tests the full "
                "archive + delivery path on demand (used by `!newsletter send`). "
                "Call this as the final step."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "markdown": {
                        "type": "string",
                        "description": "Composed newsletter markdown body.",
                    },
                    "subject_hint": {
                        "type": "string",
                        "description": (
                            "Optional single-line highlight used in the email subject. "
                            "Falls back to the date."
                        ),
                    },
                    "has_content": {
                        "type": "boolean",
                        "description": (
                            "True if the window had real activity to narrate. "
                            "False to record a \"nothing to report\" stub and skip "
                            "delivery. Defaults to True."
                        ),
                    },
                    "force_delivery": {
                        "type": "boolean",
                        "description": (
                            "Set True only when the user explicitly asked to send "
                            "(`!newsletter send`). Bypasses the interactive "
                            "short-circuit so archive + email/vault delivery run "
                            "even outside a scheduled task. Defaults to False."
                        ),
                    },
                },
                "required": ["markdown"],
            },
        },
    },
]
